# Generated by Django 4.2.16 on 2024-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="force_password_update",
            field=models.BooleanField(default=True),
        ),
    ]
