# Generated by Django 4.2.21 on 2025-08-12 15:13

from django.db import migrations


def add_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    CustomUser = apps.get_model("accounts", "CustomUser")

    admin_group = Group.objects.create(name="Admins")
    user_perms = Permission.objects.filter(codename__contains="customuser")
    admin_group.permissions.set(user_perms)

    # Assign all existing admin users to the Admins group
    admin_users = CustomUser.objects.filter(is_staff=True)
    for user in admin_users:
        user.groups.add(admin_group)


def remove_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Admins").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_force_password_update"),
    ]

    operations = [
        migrations.RunPython(add_admin_group, remove_admin_group),
    ]
