# Generated by Django 4.2.10 on 2024-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dm_regional_app", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="la",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
