# Generated by Django 4.2.10 on 2024-04-24 15:30

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dm_regional_app.utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dm_regional_app", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "historic_filters",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "prediction_filters",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "prediction_parameters",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "historic_stock",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "adjusted_costs",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SessionScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "historic_filters",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "prediction_filters",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "prediction_parameters",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "historic_stock",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "adjusted_costs",
                    models.JSONField(
                        decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "saved_scenario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dm_regional_app.savedscenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Scenario",
        ),
    ]
