# Generated by Django 4.2.10 on 2024-05-23 14:16

from django.db import migrations, models

import dm_regional_app.utils


class Migration(migrations.Migration):
    dependencies = [
        ("dm_regional_app", "0004_remove_savedscenario_prediction_filters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedscenario",
            name="adjusted_costs",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="savedscenario",
            name="adjusted_numbers",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="savedscenario",
            name="adjusted_rates",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="savedscenario",
            name="historic_filters",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="savedscenario",
            name="historic_stock",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="savedscenario",
            name="prediction_parameters",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="adjusted_costs",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="adjusted_numbers",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="adjusted_rates",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="historic_filters",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="historic_stock",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="prediction_parameters",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
            ),
        ),
    ]
