# Generated by Django 4.2.10 on 2024-07-22 12:38

from django.db import migrations, models

import dm_regional_app.utils


class Migration(migrations.Migration):
    dependencies = [
        ("dm_regional_app", "0004_remove_savedscenario_prediction_filters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedscenario",
            name="adjusted_proportions",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionscenario",
            name="adjusted_proportions",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
    ]
