# Generated by Django 4.2.10 on 2024-05-28 10:18

from django.db import migrations, models

import dm_regional_app.utils


class Migration(migrations.Migration):
    dependencies = [
        ("dm_regional_app", "0005_alter_savedscenario_adjusted_costs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedscenario",
            name="adjusted_costs",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="savedscenario",
            name="adjusted_numbers",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="savedscenario",
            name="adjusted_rates",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="adjusted_costs",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="adjusted_numbers",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionscenario",
            name="adjusted_rates",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
    ]
