# Generated by Django 4.2.10 on 2024-07-31 13:31

from django.db import migrations, models

import dm_regional_app.utils


class Migration(migrations.Migration):
    dependencies = [
        ("dm_regional_app", "0005_savedscenario_adjusted_proportions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedscenario",
            name="inflation_parameters",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionscenario",
            name="inflation_parameters",
            field=models.JSONField(
                decoder=dm_regional_app.utils.DateAwareJSONDecoder,
                encoder=dm_regional_app.utils.SeriesAwareJSONEncoder,
                null=True,
            ),
        ),
    ]
