# Generated by Django 4.2.16 on 2024-10-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dm_regional_app", "0007_datasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datasource",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
