# Generated by Django 4.2.16 on 2024-12-13 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dm_regional_app",
            "0009_rename_show_instructions_profile_show_filtering_instructions_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasource",
            old_name="end_date",
            new_name="data_end_date",
        ),
        migrations.RenameField(
            model_name="datasource",
            old_name="start_date",
            new_name="data_start_date",
        ),
    ]
